name: wafid_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # ui
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.8
  font_awesome_icon_class: ^0.0.6
  lottie: ^3.1.3
  modal_bottom_sheet: ^3.0.0
  iconly: ^1.0.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0

  # stats & genrator
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  #firebase
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3

  #networking
  cached_network_image: ^3.4.1
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  easy_localization: ^3.0.7
  flutter_secure_storage: ^9.2.2

  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  pagination_flutter: ^0.0.8
  permission_handler: ^11.3.1

  pull_to_refresh: ^2.0.0

  flutter_native_splash: ^2.4.6
  bounce: ^1.0.2
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
